eos2m0f_100 : True 64 Job failed: (<class 'Exception'>, Exception("Failed to submit Job: [(<class 'Exception'>, Exception('Job failed: ERROR'), <traceback object at 0x1048ed8c0>)]"), <traceback object at 0x1048ed880>)
eos2m0f_100 : True 63 Job failed: (<class 'Exception'>, Exception('Failed to submit Job: [(<class \'requests.exceptions.ConnectionError\'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host=\'localhost\', port=8080): Max retries exceeded with url: /api/work-requests/63?include_result=True&csv_result=True (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x1047b58c0>: Failed to establish a new connection: [Errno 61] Connection refused\'))")), <traceback object at 0x1047f4f80>)]'), <traceback object at 0x1047f5f80>)
eos2m0f_100 : True 62 Job failed: (<class 'Exception'>, Exception('Failed to submit Job: [(<class \'requests.exceptions.ConnectionError\'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host=\'localhost\', port=8080): Max retries exceeded with url: /api/work-requests/62?include_result=True&csv_result=True (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x1025958c0>: Failed to establish a new connection: [Errno 61] Connection refused\'))")), <traceback object at 0x1025d4d80>)]'), <traceback object at 0x1025d4cc0>)
