eos2m0f_100 : True 59 Job failed: (<class 'Exception'>, Exception('Failed to submit Job: [(<class \'requests.exceptions.ConnectionError\'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host=\'localhost\', port=8080): Max retries exceeded with url: /api/work-requests/59?include_result=True&csv_result=True (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x1061fe030>: Failed to establish a new connection: [Errno 61] Connection refused\'))")), <traceback object at 0x10623d500>)]'), <traceback object at 0x10623d140>)
eos2m0f_100 : True 61 Job failed: (<class 'Exception'>, Exception('Failed to submit Job: [(<class \'requests.exceptions.ConnectionError\'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host=\'localhost\', port=8080): Max retries exceeded with url: /api/work-requests/61?include_result=True&csv_result=True (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x104792030>: Failed to establish a new connection: [Errno 61] Connection refused\'))")), <traceback object at 0x10503d4c0>)]'), <traceback object at 0x10503dac0>)
eos2m0f_100 : True 60 Job failed: (<class 'Exception'>, Exception('Failed to submit Job: [(<class \'requests.exceptions.ConnectionError\'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host=\'localhost\', port=8080): Max retries exceeded with url: /api/work-requests/60?include_result=True&csv_result=True (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x103a0e030>: Failed to establish a new connection: [Errno 61] Connection refused\'))")), <traceback object at 0x103a4d3c0>)]'), <traceback object at 0x103a4d640>)
